### ISSUE TITLE
Add `files` to `package.json`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [feross/bittorrent-dht#145]
This would prevent the `test` folder from being published to NPM.  It'd shave like 40-some KB off the package.  I can submit a PR if that is alright.

**Comment by feross** [comment]
I personally don't think it's a good idea to ignore the `test/` folder. That's documentation for the module that will now be missing when you're offline and need to look inside `node_modules/buffer`.

Ignoring huge test files is a good idea, but ignoring a few text files won't make a meaningful difference. `npm install` is primarily slow because of latency and roundtrips, in my experience. I don't think this is the right tradeoff.

Previous discussions:

https://github.com/nodejs/readable-stream/pull/100
https://github.com/rvagg/through2/pull/36
https://github.com/substack/node-browserify/issues/1093
https://github.com/crypto-browserify/sha.js/issues/5
https://github.com/feross/string-to-stream/pull/1
https://github.com/beatgammit/base64-js/pull/16
https://github.com/mafintosh/csv-parser/pull/43
https://github.com/feross/buffer/pull/98
